# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interview.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'interview.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterview.proto\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x08Response\x12\x13\n\x0bresponseLLM\x18\x01 \x01(\t27\n\rInterviewChat\x12&\n\x0bgetResponse\x12\x08.Message\x1a\t.Response(\x01\x30\x01\x42/\n\x12\x63om.interview.chatB\x17InterviewChatOuterClassP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interview_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.interview.chatB\027InterviewChatOuterClassP\001'
  _globals['_MESSAGE']._serialized_start=19
  _globals['_MESSAGE']._serialized_end=45
  _globals['_RESPONSE']._serialized_start=47
  _globals['_RESPONSE']._serialized_end=78
  _globals['_INTERVIEWCHAT']._serialized_start=80
  _globals['_INTERVIEWCHAT']._serialized_end=135
# @@protoc_insertion_point(module_scope)
